version: '3'

services:
  db:
    image: 2313175k/mysql:latest
    ports:
      - "9906:3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
